extends SceneTree
## Studio preview for the .glb props generated by tools/lowpoly/.
##
## WHAT THIS IS FOR, AND WHAT IT IS NOT FOR.
##
## It answers questions about the MODEL: is the silhouette right, are the
## proportions right, does it stand on the floor, are any faces inside out,
## are there holes, does the hardware read at a distance, does it look like the
## thing it is supposed to be. For that a neutral rig is better than the real
## room, because in the real room a bad model and a dark corner look the same.
##
## It does NOT answer questions about placement or final lighting. A prop is
## only signed off once it has been captured where it actually stands, in
## FirstMuseumMap, through test_decor_capture.gd.
##
## Run it WITHOUT --headless (the capture needs a real swapchain):
##
##   "<godot>" --path . --script res://game/test_lowpoly_preview.gd
##
## Output: res://shots/lowpoly_preview/{<name>.png, view/<name>.jpg, tiles/}

const Shots := preload("res://game/AgentShots.gd")
const MapModels := preload("res://game/MapModels.gd")

const OUT_DIR := "res://shots/lowpoly_preview"
const SETTLE_FRAMES := 24
const SHOT_FRAMES := 6
const TILES := 2

## Floor cabinets, left to right, all facing -Z (out of the back wall).
const FLOOR_MODELS := [
	{"name": "lp_metal_locker", "x": -2.40},
	{"name": "lp_filing_cabinet", "x": -0.90},
	{"name": "lp_shelf_unit", "x": 0.70},
]
## Wall-mounted models: origin is the centre of the back face, so the z here is
## the wall surface itself, not a point in front of it.
const WALL_MODELS := [
	{"name": "lp_key_cabinet", "x": 2.40, "y": 1.45},
]

## Front of the back wall. Floor cabinets stand 0.28 m out from the origin so
## their backs sit just clear of it -- close enough to read as "against the
## wall", far enough that nothing z-fights.
const WALL_Z := 0.62
const ROW_Z := 0.28

## Watcher-office desk set: the replacements for the two clashing desk monitors
## the office audit found. They are reviewed on a stand-in desk rather than on
## the floor, because the whole complaint about the old ones was scale and
## facing, and neither can be judged except from the height a seated person
## actually sees them at. DESK_TOP_Y matches OfficeProps.DESK_TOP_Y exactly.
const DESK_TOP_Y := 0.74
const DESK_X := 3.90
const DESK_Z := 0.10
const DESK_MODELS := [
	{"name": "lp_desk_monitor", "x": 3.62, "y": DESK_TOP_Y, "z": 0.18},
	{"name": "lp_keyboard", "x": 3.64, "y": DESK_TOP_Y, "z": -0.12},
	{"name": "lp_pc_tower", "x": 4.95, "y": 0.0, "z": 0.16},
]

const SHOTS := [
	# Whole line-up, eye height. The first thing to check: do four cabinets in
	# one frame look like they came from the same game?
	{"name": "lineup_front", "pos": [-0.60, 1.58, -4.40],
		"look_at": [-0.30, 0.98, 0.20], "fov": 54.0},
	# Low angle. Floor contact and the plinth shadow line live or die here.
	{"name": "lineup_low", "pos": [-0.95, 0.62, -2.70],
		"look_at": [-0.60, 1.05, 0.20], "fov": 60.0},
	# Raking view along the row: checks depth, side faces and cast shadows.
	{"name": "lineup_rake", "pos": [-4.70, 1.50, -1.90],
		"look_at": [-0.40, 0.92, 0.24], "fov": 46.0},
	# From above: tops, lids, and whether anything hovers over the floor.
	{"name": "lineup_top", "pos": [-0.60, 3.30, -2.30],
		"look_at": [-0.60, 0.70, 0.26], "fov": 52.0},
	# Per-model close framing at native pixel density.
	{"name": "locker_detail", "pos": [-3.05, 1.42, -1.55],
		"look_at": [-2.40, 1.12, 0.05], "fov": 40.0},
	{"name": "filing_detail", "pos": [-1.52, 1.02, -1.30],
		"look_at": [-0.90, 0.70, 0.06], "fov": 40.0},
	{"name": "shelf_detail", "pos": [0.10, 1.28, -1.60],
		"look_at": [0.70, 1.00, 0.06], "fov": 44.0},
	{"name": "key_detail", "pos": [1.80, 1.66, -1.10],
		"look_at": [2.40, 1.45, 0.40], "fov": 34.0},
	# --- desk set -------------------------------------------------------
	# THE shot. Seated eye height, dead in front of the monitor. If the screen
	# is not squarely facing this camera the model or its origin is wrong.
	{"name": "desk_front", "pos": [3.64, 1.22, -1.60],
		"look_at": [3.64, 0.98, 0.18], "fov": 44.0},
	# Three-quarter view: proves the screen is a real recess and the head
	# actually leans back rather than standing dead vertical.
	{"name": "desk_rake", "pos": [2.10, 1.34, -1.10],
		"look_at": [3.80, 0.95, 0.16], "fov": 46.0},
	# Just above the desk surface: catches anything hovering over the slab.
	{"name": "desk_low", "pos": [3.64, 0.86, -1.10],
		"look_at": [3.70, 0.95, 0.20], "fov": 50.0},
	# Framed from the outboard side. The first version of this shot sat at
	# x 4.30 and stared straight into the desk end panel at x 4.825, which
	# filled the frame with black.
	{"name": "tower_detail", "pos": [5.72, 0.66, -1.02],
		"look_at": [4.98, 0.32, 0.14], "fov": 42.0},
	{"name": "keyboard_detail", "pos": [3.32, 1.06, -0.72],
		"look_at": [3.64, 0.76, -0.12], "fov": 38.0},
]


func _init() -> void:
	print("[LOWPOLY PREVIEW] starting")
	call_deferred("_run")


func _run() -> void:
	var stage := Node3D.new()
	stage.name = "Stage"
	root.add_child(stage)

	_build_studio(stage)
	var placed := _place_models(stage)
	if placed == 0:
		push_error("[LOWPOLY PREVIEW] nothing placed -- did the .glb files import?")
		quit(1)
		return

	var camera := Camera3D.new()
	camera.name = "PreviewCamera"
	camera.far = 400.0
	camera.near = 0.03
	camera.current = true
	stage.add_child(camera)

	for _i in range(SETTLE_FRAMES):
		await create_timer(0.033).timeout

	var viewport := root.get_viewport()
	var out_dir := ProjectSettings.globalize_path(OUT_DIR)
	DirAccess.make_dir_recursive_absolute(out_dir)

	var written := 0
	for raw: Variant in SHOTS:
		var shot: Dictionary = raw
		var shot_name := str(shot["name"])
		var camera_pos := _vec3(shot["pos"])
		var target_pos := _vec3(shot["look_at"])
		camera.fov = float(shot.get("fov", 50.0))
		for _frame in range(SHOT_FRAMES):
			await create_timer(0.033).timeout
			camera.global_position = camera_pos
			camera.look_at(target_pos, Vector3.UP)
		var image := viewport.get_texture().get_image()
		var result := Shots.save_set(image, out_dir, shot_name, TILES)
		Shots.report(result, "LOWPOLY")
		written += 1

	print("[LOWPOLY PREVIEW] done: %d shots -> %s" % [written, out_dir])
	quit()


## A neutral dark room: dark concrete floor, one back wall, two hard point
## lights and almost no ambient. Deliberately close to the game's lighting
## budget -- a model that only reads under a studio softbox is a model that
## will disappear in this museum.
func _build_studio(stage: Node3D) -> void:
	var world_env := WorldEnvironment.new()
	var env := Environment.new()
	env.background_mode = Environment.BG_COLOR
	env.background_color = Color(0.021, 0.023, 0.027)
	env.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	env.ambient_light_color = Color(0.34, 0.38, 0.44)
	env.ambient_light_energy = 0.11
	env.fog_enabled = false
	world_env.environment = env
	stage.add_child(world_env)

	var floor_mesh := MeshInstance3D.new()
	floor_mesh.name = "Studio Floor"
	var plane := PlaneMesh.new()
	plane.size = Vector2(16.0, 16.0)
	floor_mesh.mesh = plane
	floor_mesh.material_override = _studio_material(Color(0.128, 0.124, 0.112))
	stage.add_child(floor_mesh)

	var wall := MeshInstance3D.new()
	wall.name = "Studio Wall"
	var wall_box := BoxMesh.new()
	wall_box.size = Vector3(13.0, 3.20, 0.20)
	wall.mesh = wall_box
	wall.position = Vector3(0.0, 1.60, WALL_Z + 0.10)
	wall.material_override = _studio_material(Color(0.152, 0.148, 0.138))
	stage.add_child(wall)

	# Stand-in desk. Not a prop and not meant to be reviewed -- it exists only
	# so the desk set is judged at working height.
	_add_studio_box(stage, "Desk Top",
		Vector3(DESK_X, DESK_TOP_Y - 0.0225, DESK_Z),
		Vector3(1.90, 0.045, 0.75), Color(0.118, 0.100, 0.076))
	_add_studio_box(stage, "Desk End West",
		Vector3(DESK_X - 0.925, 0.3475, DESK_Z),
		Vector3(0.050, 0.695, 0.700), Color(0.104, 0.088, 0.068))
	_add_studio_box(stage, "Desk End East",
		Vector3(DESK_X + 0.925, 0.3475, DESK_Z),
		Vector3(0.050, 0.695, 0.700), Color(0.104, 0.088, 0.068))

	# Key light: hard, slightly warm, high and to the left, shadows on.
	var key := OmniLight3D.new()
	key.name = "Key Light"
	key.position = Vector3(-1.90, 2.70, -2.30)
	key.light_color = Color(1.0, 0.93, 0.82)
	key.light_energy = 3.4
	key.omni_range = 11.0
	key.shadow_enabled = true
	stage.add_child(key)

	# Fill: cold, weak, opposite side, no shadow. Just enough to keep the
	# unlit sides from going to pure black and hiding a hole.
	var fill := OmniLight3D.new()
	fill.name = "Fill Light"
	fill.position = Vector3(2.90, 1.80, -2.60)
	fill.light_color = Color(0.72, 0.80, 0.95)
	fill.light_energy = 1.05
	fill.omni_range = 10.0
	fill.shadow_enabled = false
	stage.add_child(fill)

	# Third light, over the desk station. The other two sit at x -1.90 and
	# x 2.90, so without this one the desk set is 4 m from any light source and
	# renders as a silhouette -- hiding exactly the defects this rig exists to
	# catch. Same hard, warm, shadow-casting character as the main key.
	var desk_key := OmniLight3D.new()
	desk_key.name = "Desk Key Light"
	desk_key.position = Vector3(DESK_X + 0.30, 2.35, -1.70)
	desk_key.light_color = Color(1.0, 0.95, 0.86)
	desk_key.light_energy = 1.5
	desk_key.omni_range = 7.5
	desk_key.shadow_enabled = true
	stage.add_child(desk_key)


func _add_studio_box(stage: Node3D, box_name: String, centre: Vector3,
		size: Vector3, albedo: Color) -> void:
	var node := MeshInstance3D.new()
	node.name = box_name
	var box := BoxMesh.new()
	box.size = size
	node.mesh = box
	node.position = centre
	node.material_override = _studio_material(albedo)
	stage.add_child(node)


func _studio_material(albedo: Color) -> StandardMaterial3D:
	var mat := StandardMaterial3D.new()
	mat.albedo_color = albedo
	mat.roughness = 0.95
	mat.metallic = 0.0
	mat.metallic_specular = 0.15
	return mat


## Place every model through MapModels.place(), not by loading the .glb
## directly. That way this preview also proves the loader can find files in
## models/lowpoly/ and that the collision pass does not choke on them.
func _place_models(stage: Node3D) -> int:
	var placed := 0
	for raw: Variant in FLOOR_MODELS:
		var entry: Dictionary = raw
		var model_name := str(entry["name"])
		var node := MapModels.place(stage, model_name,
			Vector3(float(entry["x"]), 0.0, ROW_Z))
		if node == null:
			push_error("[LOWPOLY PREVIEW] not found: %s" % model_name)
			continue
		_report_bounds(model_name, node)
		placed += 1
	for raw: Variant in WALL_MODELS:
		var entry: Dictionary = raw
		var model_name := str(entry["name"])
		var node := MapModels.place(stage, model_name,
			Vector3(float(entry["x"]), float(entry["y"]), WALL_Z))
		if node == null:
			push_error("[LOWPOLY PREVIEW] not found: %s" % model_name)
			continue
		_report_bounds(model_name, node)
		placed += 1
	for raw: Variant in DESK_MODELS:
		var entry: Dictionary = raw
		var model_name := str(entry["name"])
		var node := MapModels.place(stage, model_name,
			Vector3(float(entry["x"]), float(entry["y"]), float(entry["z"])))
		if node == null:
			push_error("[LOWPOLY PREVIEW] not found: %s" % model_name)
			continue
		_report_bounds(model_name, node)
		placed += 1
	return placed


## Numeric proof to sit alongside the pictures. A model that floats 3 cm over
## the floor or sinks 2 cm into it is obvious here and easy to miss in a JPEG,
## so both checks get run: the number and the image.
func _report_bounds(model_name: String, node: Node3D) -> void:
	var state := {"valid": false, "aabb": AABB()}
	_collect_bounds(node, state)
	if not bool(state["valid"]):
		push_warning("[LOWPOLY PREVIEW] no visible mesh: %s" % model_name)
		return
	var box: AABB = state["aabb"]
	print("[LOWPOLY] %-20s floor_y %+.4f  size %5.3f x %5.3f x %5.3f"
		% [model_name, box.position.y, box.size.x, box.size.y, box.size.z])


func _collect_bounds(node: Node, state: Dictionary) -> void:
	if node is MeshInstance3D:
		var mesh_node := node as MeshInstance3D
		if mesh_node.visible and mesh_node.mesh != null:
			var world_box: AABB = mesh_node.global_transform * mesh_node.mesh.get_aabb()
			if bool(state["valid"]):
				state["aabb"] = (state["aabb"] as AABB).merge(world_box)
			else:
				state["aabb"] = world_box
				state["valid"] = true
	for child in node.get_children():
		_collect_bounds(child, state)


func _vec3(value: Variant) -> Vector3:
	if typeof(value) != TYPE_ARRAY or value.size() < 3:
		return Vector3.ZERO
	return Vector3(float(value[0]), float(value[1]), float(value[2]))
